# Generated by Django 4.2.4 on 2023-09-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao24', models.CharField(blank=True, max_length=60, null=True)),
                ('registration', models.CharField(blank=True, max_length=60, null=True)),
                ('manufacturericao', models.CharField(blank=True, max_length=60, null=True)),
                ('manufacturername', models.CharField(blank=True, max_length=60, null=True)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('typecode', models.CharField(blank=True, max_length=60, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=60, null=True)),
                ('linenumber', models.CharField(blank=True, max_length=60, null=True)),
                ('icaoaircrafttype', models.CharField(blank=True, max_length=60, null=True)),
                ('operator', models.CharField(blank=True, max_length=60, null=True)),
                ('operatorcallsign', models.CharField(blank=True, max_length=60, null=True)),
                ('operatoricao', models.CharField(blank=True, max_length=60, null=True)),
                ('operatoriata', models.CharField(blank=True, max_length=60, null=True)),
                ('owner', models.CharField(blank=True, max_length=60, null=True)),
                ('testreg', models.CharField(blank=True, max_length=60, null=True)),
                ('registered', models.CharField(blank=True, max_length=60, null=True)),
                ('reguntil', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('built', models.CharField(blank=True, max_length=60, null=True)),
                ('firstflightdate', models.CharField(blank=True, max_length=60, null=True)),
                ('seatconfiguration', models.CharField(blank=True, max_length=60, null=True)),
                ('engines', models.CharField(blank=True, max_length=60, null=True)),
                ('modes', models.BooleanField(blank=True, null=True)),
                ('adsb', models.BooleanField(blank=True, null=True)),
                ('acars', models.BooleanField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=60, null=True)),
                ('categoryDescription', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
